package window;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.RadioMenuItem;

import javafx.scene.control.ToggleGroup;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.awt.Desktop;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;

import javafx.event.ActionEvent;
import javafx.scene.Scene;
import javafx.scene.control.MenuItem;

public class MainWindowController {
	@FXML
	private MenuItem MENUITEM_FILE_NEW;
	@FXML
	private MenuItem MENUITEM_FILE_OPEN;
	@FXML
	private MenuItem MENUITEM_FILE_CLOSE;
	@FXML
	private MenuItem MENUITEM_FILE_EXPORTAS_TEXTFILE;
	@FXML
	private MenuItem MENUITEM_FILE_EXPORTAS_EXCEL;
	@FXML
	private MenuItem MENUITEM_EXIT;
	@FXML
	private MenuItem MENUITEM_EDIT_ADDCOURSES;
	@FXML
	private MenuItem MENUITEM_EDIT_CUT;
	@FXML
	private MenuItem MENUITEM_EDIT_COPY;
	@FXML
	private MenuItem MENUITEM_EDIT_PASTE;
	@FXML
	private MenuItem MENUITEM_EDIT_DELETE;
	@FXML
	private MenuItem MENUITEM_PROGRAM_AUTOSCHEDULE;
	@FXML
	private RadioMenuItem MENUITEM_WINDOW_THEME_MODENA;
	@FXML
	private ToggleGroup toggleTheme;
	@FXML
	private RadioMenuItem MENUITEM_WINDOW_THEME_CASPIAN;
	@FXML
	private MenuItem MENUITEM_HELP_ABOUT;
	@FXML
	private MenuItem MENUITEM_HELP_CHECKFORUPDATES;

	// Event Listener on MenuItem[#MENUITEM_FILE_NEW].onAction
	@FXML
	public void eventNew(ActionEvent event) {
		// XXX
		try {
			Stage newWindow = new Stage();
			AnchorPane root = FXMLLoader.load(getClass().getResource("NewWindow.fxml"));
			Scene scene = new Scene(root);
			newWindow.setScene(scene); 
			newWindow.setResizable(true);
			newWindow.setTitle("MeowScheduler - New Timetable");
			newWindow.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	// Event Listener on MenuItem[#MENUITEM_FILE_OPEN].onAction
	@FXML
	public void eventOpen(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_FILE_CLOSE].onAction
	@FXML
	public void eventClose(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_FILE_EXPORTAS_TEXTFILE].onAction
	@FXML
	public void eventExportasTextfile(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_FILE_EXPORTAS_EXCEL].onAction
	@FXML
	public void eventExportasExcel(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_EXIT].onAction
	@FXML
	public void eventExit(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_EDIT_ADDCOURSES].onAction
	@FXML
	public void eventAddCourses(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_EDIT_CUT].onAction
	@FXML
	public void eventCut(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_EDIT_COPY].onAction
	@FXML
	public void eventCopy(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_EDIT_PASTE].onAction
	@FXML
	public void eventPaste(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_EDIT_DELETE].onAction
	@FXML
	public void eventDelete(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_PROGRAM_AUTOSCHEDULE].onAction
	@FXML
	public void eventAutoSchedule(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioMenuItem[#MENUITEM_WINDOW_THEME_MODENA].onAction
	@FXML
	public void eventThemeSetModena(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioMenuItem[#MENUITEM_WINDOW_THEME_MODENA].onAction
	@FXML
	public void eventThemeSetCaspian(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#MENUITEM_HELP_ABOUT].onAction
	@FXML
	public void eventAbout(ActionEvent event) {
			try {
				URI uri = new URI("https://henryouyang1230.github.io/MeowScheduler/");
				Desktop.getDesktop().browse(uri);
			} catch (URISyntaxException | IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
	
	// Event Listener on MenuItem[#MENUITEM_HELP_CHECKFORUPDATES].onAction
	@FXML
	public void eventCheckForUpdates(ActionEvent event) {
		try {
			URI uri = new URI("https://henryouyang1230.github.io/MeowScheduler/");
			Desktop.getDesktop().browse(uri);
		} catch (URISyntaxException | IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
